// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
export interface BlockCarousel {
  items: Image[];
  component: "block_carousel";
  _uid: string;
}

export interface BlockHero {
  media_mobile_poster?: StoryblokAsset;
  media_mobile?: StoryblokAsset;
  media_desktop_poster?: StoryblokAsset;
  media_desktop?: StoryblokAsset;
  component: "block_hero";
  _uid: string;
}

export interface BlockMedia {
  background?: number | string;
  colour?: number | string;
  media: StoryblokAsset;
  caption?: string;
  ratio?: number | string;
  column_start: number | string;
  column_end: number | string;
  component: "block_media";
  _uid: string;
}

export interface BlockMediaText {
  background?: number | string;
  colour?: number | string;
  title?: string;
  media?: StoryblokAsset;
  ratio?: number | string;
  text?: StoryblokRichtext;
  component: "block_media_text";
  _uid: string;
}

export interface BlockNewsletter {
  background?: number | string;
  colour?: number | string;
  title?: string;
  media?: StoryblokAsset;
  ratio?: number | string;
  text?: StoryblokRichtext;
  hidden?: boolean;
  component: "block_newsletter";
  _uid: string;
}

export interface BlockText {
  text?: StoryblokRichtext;
  component: "block_text";
  _uid: string;
}

export interface BlockTextGroup {
  items?: TextItem[];
  contact?: StoryblokRichtext;
  component: "block_text_group";
  _uid: string;
}

export interface Image {
  image: StoryblokAsset;
  caption?: string;
  component: "image";
  _uid: string;
}

export interface Link {
  title: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "link";
  _uid: string;
}

export interface LinkList {
  items: Link[];
  component: "link_list";
  _uid: string;
}

export interface Page {
  hero?: BlockHero[];
  blocks?: (BlockCarousel | BlockHero | BlockMedia | BlockMediaText | BlockNewsletter | BlockText | BlockTextGroup)[];
  seo: Seo[];
  component: "page";
  _uid: string;
}

export interface Seo {
  seo_title?: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "seo";
  _uid: string;
}

export interface Settings {
  address?: StoryblokRichtext;
  address_link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  socials?: SocialItem[];
  footer_links?: Link[];
  component: "settings";
  _uid: string;
}

export interface SocialItem {
  title: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "social_item";
  _uid: string;
}

export interface TextItem {
  title: string;
  copy?: StoryblokRichtext;
  component: "text_item";
  _uid: string;
}
